export const SWITCH_THEME = "SWITCH_THEME";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_RECENT_PRODUCTS = "UPDATE_USER_RECENT_PRODUCTS";

export const ADD_IN_USERS = "ADD_IN_USERS";
export const UPDATE_IN_USERS = "UPDATE_IN_USERS";
export const UPDATE_USERS_RECENT_PRODUCTS = "UPDATE_USERS_RECENT_PRODUCTS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_CATEGORY_PRODUCTS_SUCCESS = "GET_CATEGORY_PRODUCTS_SUCCESS";
export const GET_CATEGORY_PRODUCTS_ERROR = "GET_CATEGORY_PRODUCTS_ERROR";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_ERROR = "GET_ONE_PRODUCT_ERROR";
